# Generated by Django 2.2.14 on 2022-06-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'blue'), ('S', 'greeen'), ('D', 'red')], max_length=1),
        ),
    ]
