# Generated by Django 2.2.14 on 2022-06-21 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_shop', '0004_auto_20220621_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
